#!/bin/bash

DEST=$HOME/Downloads/Videos

mkdir -p $DEST

URL=$(xclip -o -selection clipboard)

[ -z $(echo "$URL" | grep -E '^https://www.youtube.com|^https://youtu.be|^https://twitter.com|^https://soundcloud.com') ] &&
	notify-send "The URL is not compatible." &&
	exit 1

FILENAME=$(yt-dlp --print filename -o "%(title)s-%(uploader)s.%(ext)s" "$URL") &&
notify-send "Downloading $FILENAME" &&
cd $DEST &&
yt-dlp --external-downloader aria2c --external-downloader-args "-j 16 -x 16 -s 16 -k 1M" --write-srt --sub-lang en -f 'bestvideo[height<=720]+bestaudio/best[height<=720]' "$URL" -o "%(title)s-%(uploader)s.%(ext)s" &&
cd - &&
notify-send "Download Finished." ||
	notify-send "Download Failed."
